name: Publish image

description: Publishes a docker image, SBOM, scans vulns, and signs the image.

inputs:
  makefile-target:
    required: true
    description: makefile target to invoke for publishing image with docker buildx
  registry:
    required: true
    description: registry to publish image to
  registry-username:
    required: true
    description: registry credentials username
  registry-password:
    required: true
    description: registry credentials password
  repository:
    required: true
    description: repository to publish image to
  version:
    required: true
    description: published image version
  sign-image:
    required: true
    description: sign image
  sbom-name:
    required: true
    description: name of the cyclonedx sbom
  sbom-repository:
    required: true
    description: sbom repository
  signature-repository:
    required: true
    description: signature repository
  main-path:
    required: true
    description: path to main go entry point
  image-tags:
    required: false
    description: comma-separated list of tags to publish (first tag is used for build/push; others are applied to the same digest)

outputs:
  digest:
    value: ${{ steps.digest.outputs.digest }}
    description: published image digest

runs:
  using: composite
  steps:
    - uses: imjasonh/setup-crane@00c9e93efa4e1138c9a7a5c594acd6c75a2fbf0c # v0.3.0
    - shell: bash
      id: docker-publish
      env:
        REGISTRY: ${{ inputs.registry }}
        REPO: ${{ inputs.repository }}
        REGISTRY_PASSWORD: ${{ inputs.registry-password }}
        COSIGN_REPOSITORY: ${{ inputs.sbom-repository }}
      run: |
        set -euo pipefail
        # Determine tags input: prefer image-tags, fallback to image-tag
        TAGS_INPUT="${{ inputs.image-tags }}"
        if [ -z "${TAGS_INPUT}" ]; then
          TAGS_INPUT="${{ inputs.image-tag }}"
        fi
        # Normalize and split into array
        TAGS_INPUT=$(echo "${TAGS_INPUT}" | tr -d ' ')
        IFS=',' read -r -a TAGS <<< "${TAGS_INPUT}"
        PRIMARY_TAG="${TAGS[0]:-}"
        if [ -z "${PRIMARY_TAG}" ]; then
          echo "Error: no image tag provided. Set 'image-tags' or 'image-tag'." >&2
          exit 1
        fi
        export IMAGE_TAG="${PRIMARY_TAG}"
        echo "Building and publishing primary tag: ${IMAGE_TAG}"
        make ${{ inputs.makefile-target }}
        # Compute digest from the primary tag
        DIGEST=$(crane digest ghcr.io/${{ github.repository }}:${PRIMARY_TAG})
        echo "Primary digest: ${DIGEST}"
        echo "digest=ghcr.io/${{ github.repository }}@${DIGEST}" >> $GITHUB_OUTPUT
        # Apply additional tags to the same digest
        if [ ${#TAGS[@]} -gt 1 ]; then
          for t in "${TAGS[@]}"; do
            [ -z "$t" ] && continue
            if [ "$t" != "$PRIMARY_TAG" ]; then
              echo "Tagging digest ${DIGEST} as: $t"
              crane tag ghcr.io/${{ github.repository }}@${DIGEST} "$t"
            fi
          done
        fi
    - uses: CycloneDX/gh-gomod-generate-sbom@d4aee0cf5133055dbd98899978246c10c18c440f # v1.1.0
      with:
        version: v1
        args: app -licenses -json -output ${{ inputs.sbom-name }}-bom.cdx.json -main ${{ inputs.main-path }}
    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: ${{ inputs.sbom-name }}-bom-cdx
        path: ${{ inputs.sbom-name }}-bom.cdx.json
    - shell: bash
      if: ${{ inputs.sign-image == 'true' }}
      env:
        COSIGN_REPOSITORY: ${{ inputs.signature-repository }}
      run: |
        set -e
        cosign sign --yes \
          -a "repo=${{ github.repository }}" \
          -a "workflow=${{ github.workflow }}" \
          -a "ref=${{ github.sha }}" \
          ${{ steps.docker-publish.outputs.digest }}
    - shell: bash
      env:
        COSIGN_REPOSITORY: ${{ inputs.sbom-repository }}
      run: |
        cosign attach sbom --sbom ./${{ inputs.sbom-name }}-bom.cdx.json --type cyclonedx ${{ steps.docker-publish.outputs.digest }}
    - shell: bash
      id: digest
      run: |
        echo "The image generated is: ${{ steps.docker-publish.outputs.digest }}"
        DIGEST=$(echo ${{ steps.docker-publish.outputs.digest }} | cut -d '@' -f2)
        echo "Digest from image is: $DIGEST"
        echo "digest=$DIGEST" >> $GITHUB_OUTPUT
