apiVersion: v2
type: application
name: kyverno-notation-aws
version: v1-rc.1
appVersion: latest
description: Kyverno extension service for Notation and the AWS signer
keywords:
  - kubernetes
  - nirmata
  - AWS signer
  - notation
