apiVersion: v2
type: application
name: kyverno-notation-aws
version: 1.2.2
appVersion: v1.2.2
description: Kyverno extension service for Notation and the AWS signer
keywords:
  - kubernetes
  - nirmata
  - AWS signer
  - notation
