apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kyverno-notation-aws.clusterRoleName" . }}
  labels:
    {{- include "kyverno-notation-aws.labels" . | nindent 4 }}
rules:
- apiGroups:
  - notation.nirmata.io
  resources:
  - trustpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notation.nirmata.io
  resources:
  - trustpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - notation.nirmata.io
  resources:
  - truststores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - notation.nirmata.io
  resources:
  - truststores/finalizers
  verbs:
  - update
