{{ range $name, $secret := .Values.deployment.imagePullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ template "kyverno-notation-aws.namespace" $ }}
  labels:
    {{- include "kyverno-notation-aws.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "kyverno-notation-aws.config.imagePullSecret" $secret }}
{{ end }}
