apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kyverno-notation-aws.roleName" . }}
  namespace: {{ template "kyverno-notation-aws.namespace" . }}
  labels:
    {{- include "kyverno-notation-aws.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - "secrets"
  - "configmaps"
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
